# Docs: https://docs.codecov.io/docs/codecovyml-reference

codecov:
  require_ci_to_pass: yes

coverage:
  precision: 1
  round: down
  status:
    project:
      default:
        target: auto
    patch: no
    changes: no

comment:
  layout: "diff,files"
  require_changes: yes
