exclude: README.md
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [
            "flake8-deprecated==2.1", # Looks for method deprecations
            "flake8-use-fstring==1.4", # Enforces use of f-strings over .format and %s
          ]
        args: ["--enable-extensions=G"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.15.0"
    hooks:
      - id: mypy
        exclude: "test_*"
        additional_dependencies:
          [fastapi, pydantic, pydantic-settings, starlette, httpx]
